//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public Application()
        {
            this.SurveyLinkInfoes = new HashSet<SurveyLinkInfo>();
        }
    
        public string Name { get; set; }
        public string AppKey { get; set; }
    
        public virtual ICollection<SurveyLinkInfo> SurveyLinkInfoes { get; set; }
    }
}
