//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttributeType
    {
        public AttributeType()
        {
            this.Attributes = new HashSet<Attribute>();
            this.Entities = new HashSet<Entity>();
        }
    
        public int Id { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<Attribute> Attributes { get; set; }
        public virtual ICollection<Entity> Entities { get; set; }
    }
}
