//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity
    {
        public Entity()
        {
            this.Entity1 = new HashSet<Entity>();
            this.SurveyResults = new HashSet<SurveyResult>();
        }
    
        public int EntityId { get; set; }
        public int SurveyId { get; set; }
        public string Name { get; set; }
        public string Caption { get; set; }
        public string Id { get; set; }
        public Nullable<int> Type { get; set; }
        public string Value { get; set; }
        public Nullable<int> ParentQuestionId { get; set; }
        public Nullable<bool> IsDependency { get; set; }
        public Nullable<int> DependentAttrId { get; set; }
        public Nullable<int> DependentEntityId { get; set; }
        public Nullable<int> QuestionOrder { get; set; }
        public int Indent { get; set; }
        public Nullable<bool> IsRequired { get; set; }
    
        public virtual AttributeType AttributeType { get; set; }
        public virtual ICollection<Entity> Entity1 { get; set; }
        public virtual Entity Entity2 { get; set; }
        public virtual Survey Survey { get; set; }
        public virtual ICollection<SurveyResult> SurveyResults { get; set; }
    }
}
