//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survey
    {
        public Survey()
        {
            this.Entities = new HashSet<Entity>();
            this.SurveyLinkInfoes = new HashSet<SurveyLinkInfo>();
            this.SurveyResults = new HashSet<SurveyResult>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual ICollection<Entity> Entities { get; set; }
        public virtual ICollection<SurveyLinkInfo> SurveyLinkInfoes { get; set; }
        public virtual ICollection<SurveyResult> SurveyResults { get; set; }
    }
}
