//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyLinkInfo
    {
        public string GUID { get; set; }
        public int UserId { get; set; }
        public int SurveyId { get; set; }
        public int SurveyStatusId { get; set; }
        public string ApplicationKey { get; set; }
        public Nullable<int> ClientId { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Client Client { get; set; }
        public virtual Survey Survey { get; set; }
        public virtual SurveyStatu SurveyStatu { get; set; }
        public virtual User User { get; set; }
    }
}
